"""initial schema

Revision ID: 48501ce6db28
Revises: 
Create Date: 2026-08-22 10:47:26.963916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48501ce6db28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('razorpay_account_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_razorpay_account_id'), 'merchants', ['razorpay_account_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('created', 'authenticated', 'active', 'pending', 'halted', 'cancelled', 'completed', 'expired', 'paused', name='subscription_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('paid_count', sa.Integer(), nullable=True),
    sa.Column('remaining_count', sa.Integer(), nullable=True),
    sa.Column('auth_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('current_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_subscriptions_merchant_id_merchants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('razorpay_subscription_id', name=op.f('uq_subscriptions_razorpay_subscription_id'))
    )
    op.create_index(op.f('ix_subscriptions_merchant_id'), 'subscriptions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('razorpay_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processed', 'failed', name='event_processing_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('razorpay_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payment_events_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('razorpay_event_id', name='uq_payment_events_razorpay_event_id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_razorpay_subscription_id'), 'payment_events', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_events_subscription_id'), 'payment_events', ['subscription_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('payment_event_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('insufficient_funds', 'expired_or_invalid_card', 'bank_or_gateway_error', 'mandate_revoked', 'other', name='diagnosis_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('rules', 'llm', name='diagnosis_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('llm_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], name=op.f('fk_diagnoses_payment_event_id_payment_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_diagnoses_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses'))
    )
    op.create_index(op.f('ix_diagnoses_payment_event_id'), 'diagnoses', ['payment_event_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_subscription_id'), 'diagnoses', ['subscription_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('retry_charge', 'send_payment_link', 'escalate_manual', 'mark_dead', name='action_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('planned', 'scheduled', 'executing', 'executed', 'failed', 'cancelled', 'skipped', name='action_status', native_enum=False, create_constraint=True, length=32), server_default='planned', nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('razorpay_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('razorpay_payment_link_id', sa.String(length=64), nullable=True),
    sa.Column('guardrail_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_recovery_actions_diagnosis_id_diagnoses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_recovery_actions_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_actions'))
    )
    op.create_index(op.f('ix_recovery_actions_diagnosis_id'), 'recovery_actions', ['diagnosis_id'], unique=False)
    op.create_index('ix_recovery_actions_status_scheduled_at', 'recovery_actions', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_recovery_actions_subscription_id'), 'recovery_actions', ['subscription_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Enum('system', 'guardrail', 'llm', 'worker', 'api', 'razorpay_webhook', name='audit_actor', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('payment_event_id', sa.UUID(), nullable=True),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('recovery_action_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_audit_log_diagnosis_id_diagnoses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], name=op.f('fk_audit_log_payment_event_id_payment_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], name=op.f('fk_audit_log_recovery_action_id_recovery_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_audit_log_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_event_time'), 'audit_log', ['event_time'], unique=False)
    op.create_index(op.f('ix_audit_log_subscription_id'), 'audit_log', ['subscription_id'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('recovery_action_id', sa.UUID(), nullable=True),
    sa.Column('triggering_payment_event_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('recovered', 'still_at_risk', 'escalated', 'dead', name='outcome_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('amount_recovered', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_at_risk', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], name=op.f('fk_recovery_outcomes_recovery_action_id_recovery_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_recovery_outcomes_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_payment_event_id'], ['payment_events.id'], name=op.f('fk_recovery_outcomes_triggering_payment_event_id_payment_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_outcomes'))
    )
    op.create_index(op.f('ix_recovery_outcomes_recovery_action_id'), 'recovery_outcomes', ['recovery_action_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_subscription_id'), 'recovery_outcomes', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_outcomes_subscription_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_recovery_action_id'), table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index(op.f('ix_audit_log_subscription_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_time'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_recovery_actions_subscription_id'), table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_status_scheduled_at', table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_diagnosis_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_diagnoses_subscription_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_payment_event_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_payment_events_subscription_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_razorpay_subscription_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_merchant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_merchants_razorpay_account_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
